app/song/urls.py
from django.urls import path

from . import views

app_name = 'song'
urlpatterns = [
    path('',
         views.song_list,
         name='song-list'),
    path('search/',
         views.song_search,
         name='song-search'),
    path('search/melon/',
         views.song_search_from_melon,
         name='song-search-from-melon'),
    path('search/melon/add/',
         views.song_add_from_melon,
         name='song-add-from-melon'),
]

app/song/models.py
from django.db import models, transaction

from album.models import Album
from artist.models import Artist
from crawler.song import SongData


class SongManager(models.Manager):
    def update_or_create_from_melon_id(self, song_id):
        """
        song_id에 해당하는 Song정보를 멜론사이트에서 가져와 update_or_create를 실행
        이 때, 해당 Song의 Artist정보도 가져와 ArtistManager.update_or_create_from_melon도 실행
         그리고 해당 Song의 Album정보도 가져와서 AlbumManager.update_or_create_from_melon도 실행
            -> Album의 커버이미지도 저장해야 함

        :param song_id: 멜론 사이트에서의 곡 고유 ID
        :return: (Song instance, Bool(Song created))
        """
        song_data = SongData(song_id)
        song_data.get_detail()

        with transaction.atomic():
            album, _ = Album.objects.update_or_create_from_melon(song_data.album_id)
            artist, _ = Artist.objects.update_or_create_from_melon(song_data.artist_id)
            song, song_created = self.update_or_create(
                melon_id=song_id,
                defaults={
                    'title': song_data.title,
                    'genre': song_data.genre,
                    'lyrics': song_data.lyrics,
                    'album': album,
                }
            )

            song.artists.add(artist)
            return song, song_created


class Song(models.Model):
    melon_id = models.CharField('멜론 Song ID', max_length=20, blank=True, null=True, unique=True)
    album = models.ForeignKey(
        Album,
        verbose_name='앨범',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    artists = models.ManyToManyField(
        Artist,
        verbose_name='아티스트 목록',
        blank=True,
    )
    title = models.CharField(
        '곡 제목',
        max_length=100,
    )
    genre = models.CharField(
        '장르',
        max_length=100,
    )
    lyrics = models.TextField(
        '가사',
        blank=True,
    )

    objects = SongManager()

    @property
    def release_date(self):
        # self.album의 release_date를 리턴
        return self.album.release_date

    @property
    def formatted_release_date(self):
        return self.release_date.strftime('%Y.%m.%d')

    def __str__(self):
        # 가수명 - 곡제목 (앨범명)
        # TWICE(트와이스) - Heart Shaker (Merry & Happy)
        # 휘성, 김태우 - 호호호빵 (호호호빵)
        #  artists는 self.album의 속성
        # if self.album:
        #     return '{artists} - {title} ({album})'.format(
        #         artists=', '.join(self.album.artists.values_list('name', flat=True)),
        #         title=self.title,
        #         album=self.album.title,
        #     )
        return self.title

app/templates/song/song_list.html
{% extends 'base.html' %}
{% load song_extras %}

{% block content %}
<div class="song-list-container">
	<ul class="song-list">
		{% for song in songs %}
		<li class="song-list-item clearfix">
			<div class="li-section clearfix">
				<div class="li-section-title">제목</div>
				<div class="li-section-content">{{ song.title }}</div>
			</div>
			<div class="li-section clearfix">
				<div class="li-section-title">가사</div>
				<div class="li-section-content">{{ song.lyrics|ellipsis_line:3|linebreaksbr }}</div>
			</div>
		</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

app/templates/song/song_search.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h1><a href="{% url 'song:song-search' %}">노래 검색</a></h1>
	<!--
		1. song/urls.py에 app_name지정
		2. 각 path에 name지정
		3. <app_name>:<url_name> 형식을 사용
	-->
	<form action="" method="get">
		<input id="input-keyword" type="text" name="keyword" value="{{ request.GET.keyword }}">
		<button type="submit">검색</button>
	</form>
	<!--
		for문을 순회하면서 include태그를 순회문 안에서 1번만 사용해서 3개를 출력할 수 있도록
		views.py의 내용을 수정
	-->
	{% for song_info in song_infos %}
		{% include 'include/song_search_result.html' with type=song_info.type songs=song_info.songs only %}
	{% endfor %}

</div>
{% endblock %}

app/templates/song/song_search_from_melon.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>멜론에서 노래 검색</h3>
	<form action="">
		<input type="text" name="keyword">
		<button type="submit">검색</button>
	</form>

	<ul>
		{% for song_info in song_info_list %}
		<li>
			<div>
				<span>{{ song_info.song_id }} | {{ song_info.title }}</span>
			</div>
			<div>{{ song_info.artist }}</div>
			<form action="{% url 'song:song-add-from-melon' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="song_id" value="{{ song_info.song_id }}">
				<button type="submit">DB에 추가하기</button>
			</form>
		</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}